# Generated by Django 4.1.4 on 2022-12-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_people_email_people_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='people',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='username'),
        ),
    ]
