# Generated by Django 4.1.4 on 2023-01-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_people_email_alter_people_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='profile picture'),
        ),
    ]
